fullnameOverride:
namespaceOverride:

deployment:
  annotations: {}
  labels: {}
  autoscale:
    enabled: true
  replicas:

pod:
  annotations: {}
  labels: {}

image:
  repository:
  tag:
  pullPolicy:

awx:
  appCredentials:
    existingSecret:
  secretKey:
    existingSecret:
  settings:
    existingConfigMap:
  nginxConfig:
    existingConfigMap:
  receptorConfig:
    existingSecret:
  

  

