{{- $fullName := include "helm.fullname" . }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
 name: {{ $fullName }}-sa-secret
 annotations:
   kubernetes.io/service-account.name: {{ $fullName }}