{{- $fullName := include "helm.fullname" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespaceOverride | default "default" }}
  labels:
    {{ include "helm.labels.standard" . | indent 4 | trim }}
    {{ include "helm.labels.custom" . | indent 4 | trim }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}