{{- $fullName := include "helm.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespaceOverride | default "default" }}
  labels:
    {{ include "helm.labels.standard" . | indent 4 | trim }}
    {{ include "helm.labels.custom" . | indent 4 | trim }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}

spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8052
  selector:
    {{ include "helm.labels.selector" . | indent 6 | trim }}
  sessionAffinity: None
  type: ClusterIP

  