fullnameOverride:
namespaceOverride: "default"
targetCloud: "IBM"

config:
  existingSecret:
  git:
    address: 
    branch: 
    path:
  insecure:
    brokerPassword:
    brokerUsername:
    gitUsername:
    gitKey:
    gitPassword:

deployment:
  autoscaling: 
    horizontal:
      enabled: "true"
      maxReplicas: "5"
      minReplicas: "1"
      targetCPUUtilizationPercentage: "90"
    vertical:
      enabled: "true"
      vpaMode: "Initial"
  security:
    pod:
      enabled: false
    container:
      enabled: false
  replicas: 
  labels: {}
  annotations: {}

service:
  labels: {}
  annotations: {}

image:
  repository: "ghcr.io/fnts-public/openservicebroker"
  tag: "latest"
  pullPolicy: "IfNotPresent"