{{ if not .Values.config.existingSecret }}
{{- $fullName := include "helm.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespaceOverride | default "default" }}
  labels:
    {{ include "helm.labels.standard" . | indent 4 | trim }}
data:
  APP_BASIC_AUTH_PASSWORD: {{ .Values.config.insecure.brokerPassword | default (include "helm.password" .) | b64enc}}
  APP_BASIC_AUTH_USERNAME: {{ .Values.config.insecure.brokerUsername | default (.Values.targetCloud | default "IBM" ) | b64enc}}
  GIT_PASSWORD: {{ .Values.config.insecure.gitPassword | default "gitpw" | b64enc}}
  GIT_SSH_KEY: {{ .Values.config.insecure.gitKey | default "gitssh" | b64enc}}
  GIT_USERNAME: {{ .Values.config.insecure.gitUsername | default "gituser" | b64enc}}

{{- end -}}