{{- $fullName := include "helm.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespaceOverride | default "default" }}
  labels:
    {{ include "helm.labels.standard" . | indent 4 | trim }}
    {{ include "helm.labels.custom" . | indent 4 | trim }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8075
      protocol: TCP
      name: http
    
  selector:
    {{ include "helm.labels.selector" . | indent 4 | trim }}
    {{ include "helm.labels.standard" . | indent 4 | trim }}